modLoader="javafml"
loaderVersion="${forgeLoaderRange}"
license="MIT"
issueTrackerURL="${modIssueTracker}"

[[mods]]
modId="example"
version="${modVersion}"
displayName="${modName}"
#updateJSONURL="http://myurl.me/"
displayURL="https://example.example"
#logoFile="icon.png"
#credits="Thanks for this example mod goes to Java"
authors="${modAuthor}"
#displayTest="MATCH_VERSION"

description='''
${modDescription}
'''

[[dependencies.example]]
   modId="forge"
   mandatory=true
   versionRange="${forgeLoaderRange}"
   ordering="NONE"
   side="BOTH"

[[dependencies.example]]
   modId="minecraft"
   mandatory=true
   versionRange="${forgeMinecraftVersionRange}"
   ordering="NONE"
   side="BOTH"

[[dependencies.example]]
   modId = "architectury"
   mandatory = true
   versionRange = "${forgeArchitecturyVersionRange}"
   ordering = "NONE"
   side = "BOTH"