modLoader="javafml"
loaderVersion="${forge_loader_range}"
license="MIT"
issueTrackerURL="${mod_issueTracker}"

[[mods]]
modId="example"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="http://myurl.me/"
displayURL="https://example.example"
logoFile="icon.png"
#credits="Thanks for this example mod goes to Java"
authors="${mod_author}"
#displayTest="MATCH_VERSION"

description='''
${mod_description}
'''

[[dependencies.example]]
   modId="forge"
   mandatory=true
   versionRange="${forge_loader_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.example]]
   modId="minecraft"
   mandatory=true
   versionRange="${forge_minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.example]]
   modId = "architectury"
   mandatory = true
   versionRange = "${forge_architectury_version_range}"
   ordering = "NONE"
   side = "BOTH"